version: '3.2'

volumes:
  document_data:
  document_log:

services:
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-db
    restart: always
    #    networks:
            #- nextcloud_net
    expose:
      - 3306
    volumes:
      - /data/nextcloud/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE_FILE=/run/secrets/db_file
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_pass
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pass
      - MYSQL_INITDB_SKIP_TZINFO=1
    secrets:
      - db_file
      - db_pass
      - db_user
      - db_root_pass

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis

  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    #networks:
            #- nextcloud_net
    ports:
      - "80:80"
    expose:
      - 80
      - 443
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - /data/nextcloud/app/html:/var/www/html
      - /data/nextcloud/app/config:/var/www/html/config
      - /data/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/app/data:/var/www/html/data
      - /data/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_TYPE=mysql
      - REDIS_HOST=nextcloud-redis
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE_FILE=/run/secrets/db_file
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_pass
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pass
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost tortique.tech nextcloud-db
      - NEXTCLOUD_HOSTNAME=tortique.tech
      - VIRTUAL_HOST=tortique.tech
        #- LETSENCRYPT_HOST=tortique.tech
        #- LETSENCRYPT_EMAIL=root@tortique.tech
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - db_file
      - db_pass
      - db_user
      - db_root_pass

# document-server:
#   image: onlyoffice/documentserver:latest
#   stdin_open: true
#   restart: unless-stopped
#   networks:
#     - nextcloud_net
#   tty: true
#   ports:
#     - "8889:8080"
#     - "8890:443"
#     - "8891:80"
#   volumes:
#     - document_data:/var/www/onlyoffice/Data
#     - document_log:/var/log/onlyoffice

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.secret
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.secret
  db_file:
    file: ./secrets/db_file.secret
  db_root_pass:
    file: ./secrets/db_root_pass.secret
  db_pass:
    file: ./secrets/db_pass.secret
  db_user:
    file: ./secrets/db_user.secret
